## Tuples used as records

In [ ]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)
travelers_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(travelers_ids):
    print('%s/%s' % passport)

for country, _ in travelers_ids:
    print(country)

## Tuples as Immutable Lists
This brings two keys benefits:
* **Clarity** - When you see a tuple in code, you know its length will never change
* **Performance** - A _tuple_ uses less memory than a _list_ of the same length, and it allows Python to do some optimizations.
However, be aware that the immutability of a _tuple_ only applies to the references contained in it. References in a tuple _cannot_ be deleted or replaced. But if one of those references points to a mutable object, and that object is changed, then the value of the _tuple_ changes.

In [ ]:
a = (10, 'alpha', [1, 2])
b = (10, 'alpha', [1, 2])

id(a[-1]), id(b[-1])

In [ ]:
a == b

In [ ]:
b[-1].append(99)
a == b

In [ ]:
b

In [ ]:
hash(a)

In [ ]:
c = (10, 'alpha', (1, 2))
hash(c)

## Unpacking Sequences and Iterables

In [ ]:
# Swapping variables with unpacking
a = 1
b = 2
print(a, b)
a, b = b, a
print(a, b)

In [ ]:
# Using * to Grab Excess Items
a, b, *rest = (1, 2, 3, 4)
print(a, b)
print(rest)

In [ ]:
# Unpacking parameters with * to function
print(divmod(20, 8))

t = (20, 8)
print(divmod(*t))

In [ ]:
# Unpacking with * in Function Calls and Sequence Literals
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest

fun(*[1, 2], 3, *range(4, 7))

In [ ]:
# Nested Unpacking
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for name, _, _, (lat, lon) in metro_areas:
        if lon <= 0:
            print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')

main()

## Pattern Matching with Sequences

In [ ]:
class Robot:
    def handle_command(self, message):
        match message: #1 (the number of items must mach as well)
            case ['BEEPER', frequency, times]: #2
                self.beep(times, frequency)
            case ['NECK', angle]: #3
                self.rotate_neck(angle)
            case ['LED', ident, intensity]: #4
                self.leds[ident].set_brightness(ident, intensity)
            case ['LED', ident, red, green, blue]: #5
                self.leds[ident].set_color(ident, red, green, blue)
            case _: #6
                raise InvalidCommand(message)


In [ ]:
# Destructuring nested tuples
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for record in metro_areas:
        match record: #1
            case [name, _, _, (lat, lon)] if lon <= 0: #2
                print(f'{name:15} | {lat:>9.4f} | {lon:>9.4f}')

main()

In [ ]:
a, b, *rest = (1, 2, 3, 4, 5)
print(a, b, rest)

a, b, *rest = ({"a": 1, "b": 2, "c": 3, "d": 4}).items()
print(a, b, rest)

## Slicing

In [ ]:
# examples
l = [10, 20, 30, 40, 50, 60]
print(l[:2])
print(l[2:])
print(l[:3])
print(l[3:])

print(l[:9])
print(l[-1:])
print(l[:-1])

s = "bicycle"
print(s[::3])
print(s[::-1])
print(s[::-2])

In [ ]:
# Slice Objects
invoice = """
0.....6.................................40........52...55........
1909  Pimorony PiBrella                     $17.50    3    $52.50
1489  6mm Tactile Switch x20                 $4.95    2     $9.90
1510  Panavise Jr. - PV-201                 $28.00    1    $28.00
1601  PiTFT Mini Kit 320x240                $34.95    1    $34.95
"""
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

In [ ]:
# Multidimensional Slicing and Ellipsis (...)
# Not in use in Python standard library
s = "johannes ferreira"
print(s[:8])
print(s[9:])
# print(s[9:...]) doesn't work

In [30]:
# Assigning to Slices
l = list(range(10))
print(l)

print(l[2:5])
l[2:5] = [20, 30]
print(l)

print(l[5:7])
del l[5:7]
print(l)

print(l[3::2])
l[3::2] = [11, 22]
print(l)

# when the targe of the assignment is a slice, the righthand side must be a iterable object,
# even if it has one item
# l[2:5] = 100
print(l)
l[2:5] = [100]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[6, 7]
[0, 1, 20, 30, 5, 8, 9]
[30, 8]
[0, 1, 20, 11, 5, 22, 9]
[0, 1, 20, 11, 5, 22, 9]
[0, 1, 100, 22, 9]


## Using + and * with Sequences
Both + and * always create a new object, and never change their operands.

In [3]:
l = [1, 2, 3]
print(id(l), l)
ll = l + l
print(id(ll), ll)

llll = l * 4
print(id(llll), llll)

139966277071168 [1, 2, 3]
139966276473280 [1, 2, 3, 1, 2, 3]
139966276601280 [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [6]:
# Building Lists of Lists
board = [['_'] * 3 for i in range(3)] #1
print(board)

board[1][2] = 'X' #2
print(board)

# wrong way
weird_board = [['_'] * 3] * 3 #1
print(weird_board)

weird_board[1][2] = 'O' #2
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


In [9]:
# Augmented Assigned with Sequences
l = [1, 2, 3]
print(id(l), l)

l *= 2
print(id(l), l)

t = (1, 2, 3)
print(id(t), t)

t *= 2
print(id(t), t)

139966277181184 [1, 2, 3]
139966277181184 [1, 2, 3, 1, 2, 3]
139966275363136 (1, 2, 3)
139966304020672 (1, 2, 3, 1, 2, 3)


In [12]:
# A += Assignment Puzzler
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [13]:
print(t)

(1, 2, [30, 40, 50, 60])


In [14]:
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


## list.sort Versus the sorted Build-In
The _list.sort_ method sorts a list **in place** -- that is, without making a copy. It returns _None_ to remind us that it changes the receiver and does not create a new list.

In contrast, the built-in function _sorted_ creates a new list and returns it.

In [8]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(fruits)
print(sorted(fruits))
print(sorted(fruits, reverse=True))
print(sorted(fruits, key=len))
print(sorted(fruits, key=len, reverse=True))
print(fruits)

fruits.sort()
print(fruits)

['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']
['raspberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'raspberry']
['raspberry', 'banana', 'grape', 'apple']
['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']


## When a List Is Not the Answer
The _list_ type is flexible and easy to use, but depending on specific requirements, there are better options.

In [14]:
# Arrays
# If a list only contains numbers, an array.array is a more efficient replacement. Arrays support
# all mutable sequence operations (including .pop, .insert, and .extend), as well as additional
# methods for fast loading and saving, such as .frombytes and .tofile.

from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))

In [15]:
print(floats[-1])
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

0.5100603418095596


In [16]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()

In [18]:
print(floats2[-1])
print(floats == floats2)
print(id(floats), id(floats2))

0.5100603418095596
True
140378123158368 140378123159328


In [1]:
# Memory Views

# The built-in memoryview class is a shared-memory sequence type that lets you handle slices of
# arrays without copying bytes.
# A memoryview is essentially a generalized NumPy array structure in Python itself (without the math).
# It allows you to share memory between data-structures (things like PIL images, SQLite databases,
# NumPy arrays, etc) without first copying. This is very important for large data sets.

from array import array

octets = array('B', range(6)) #1
m1 = memoryview(octets) #2
print(id(m1), m1.tolist())

m2 = m1.cast('B', [2, 3]) #3
print(id(m2), m2.tolist())

m3 = m1.cast('B', [3, 2]) #4
print(id(m3), m3.tolist())

m2[1,1] = 22 #5
m3[1,1] = 33 #6
print(octets) #7

139702449077696 [0, 1, 2, 3, 4, 5]
139702449011600 [[0, 1, 2], [3, 4, 5]]
139702449011808 [[0, 1], [2, 3], [4, 5]]
array('B', [0, 1, 2, 33, 22, 5])


In [3]:
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers) #1
print(len(memv))

print(memv[0]) #2

memv_oct = memv.cast('B') #3
print(memv_oct.tolist()) #4

memv_oct[5] = 4 #5
print(numbers)

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


In [3]:
# NumPy

# For advanced array and matrix operations, NumPy is the reason why Python became mainstream in
# scientific computing applications. NumPy implements multi-dimensional, homogeneous arrays and
# matrix types that hold not only numbers but also user-defined records, and provides efficient
# element-wise operations.

import numpy as np

a = np.arange(12)
print(a)
print(type(a))
print(a.shape)

a.shape = 3, 4
print(a)
print(a[2])
print(a[2, 1])
print(a[:, 1])
print(a.transpose())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [9]:
# Deques and Other Queues

# Inserting and removing from the head of a list (the 0-index end) is costly because the etire
# list must be shifted in memory.
# The class collections.deque is a thread-save double-ended queue designed for fast inserting
# and removing from both ends. It is also the way to go if you need to keep a list of "last
# seen items" of something of that nature, because a deque can be bounded -- i.e., created with
# a fixed maximum length. If a bounded deque is full, when you add a new item, it discards an
# item from the opposite end.

from collections import deque

dq = deque(range(10), maxlen=10) #1
print(dq)

dq.rotate(3) #2
print(dq)

dq.rotate(-4)
print(dq)

dq.appendleft(-1) #3
print(dq)

dq.extend([11, 22, 33]) #4
print(dq)

dq.extendleft([10, 20, 30, 40]) #5
print(dq)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)
